import mongoose from "mongoose";

const Schema = mongoose.Schema

const hookflowSchema = new Schema({
    userId: { // the user who is creating the webhook
        type: mongoose.Schema.Types.ObjectId,
        ref: "User",
        required: true,
        index: true
    },
    webhookName: { // user can set name of hook to track easily in future if wanna delete or update
        type: String,
        required: true,
        trim: true
    },
    webhookPath: { // this will be generated by the system and will be used to identify the webhook in future
        type: String,
        required: true,
        unique: true,
        index: true,
    },
    webhookSecret: { // when we create a webhook (lets say in github repo), we can also create a secret with it that verifies if the response is coming from a correct source, withoutt it, any hacker can send false request and waste our resources.
        type: String,
        required: false // not required but recommended, i will mention this in frontend
    },
    isHookActive: {
        type: Boolean,
        default: true
    },
    integration: {  // source from where the payload is coming from
        provider: {
            type: String,
            required: true,
            enum: ['github', 'stripe', 'discord', 'other']
        },
        verification: {
            type: Boolean,
            default: false
        }
    },
    pipeline: { // set of rules and  actions that we will be making on payload before sending it to destination
        type: Object,
        default: {}
    },
    delivery: {  // destination, where the payload will go
        destinationWebhookUrl: { // will be provided by user
            type: String,
            required: true
        },
        destination: {
            type: String,
            required: true,
            enum: ['github', 'stripe', 'discord', 'slack', 'other', 'custom']
        },
        verification: {
            type: Boolean,
            default: false
        },
        config: {
            type: Object,
            default: {}
        },
        retryCount: {
            type: Number,
            default: 3
        },
        requestTimeoutinMS: {
            type: Number,
            default: 5000
        }
    }

}, { timestamps: true })

//  this will ensure that the webhookName is unique accross all records of a specific user - this is called compound indexing
// the combination of userId and webhookName is unique, so a user can't have 2 webhooks with the same name
hookflowSchema.index({ userId: 1, webhookName: 1 }, { unique: true })

const HookflowModel = mongoose.model("Hookflow", hookflowSchema)
export default HookflowModel